export const COLLEGES = [
    // IITs
    "IIT Bombay", "IIT Delhi", "IIT Madras", "IIT Kanpur", "IIT Kharagpur", "IIT Roorkee", "IIT Guwahati", "IIT Hyderabad",
    "IIT Jodhpur", "IIT Gandhinagar", "IIT Mandi", "IIT Patna", "IIT Indore", "IIT Ropar", "IIT Bhubaneswar",
    // NITs
    "NIT Trichy", "NIT Warangal", "NIT Surathkal", "NIT Calicut", "NIT Rourkela", "NIT Durgapur", "NIT Jamshedpur",
    "NIT Kurukshetra", "NIT Agartala", "NIT Meghalaya", "NIT Mizoram", "NIT Nagaland", "NIT Sikkim", "NIT Arunachal Pradesh",
    "NIT Puducherry", "NIT Goa", "NIT Uttarakhand", "NIT Manipur", "NIT Patna", "NIT Jalandhar", "NIT Silchar", "NIT Raipur", "NIT Hamirpur",
    // Private / Others
    "BITS Pilani", "VIT Vellore", "VIT Chennai", "VIT Bhopal", "VIT AP", "SRM University", "Manipal University", "Thapar University", "Amity University",
    "Anna University", "Delhi University", "Jadavpur University",
    // Options
    "Other"
]

export const SUBJECTS = [
    "AWS Cloud Practitioner",
    "AWS Solution Architect",
    "Advanced Java Programming",
    "Advanced Technical Communication",
    "Agile Software Development",
    "Applied Cryptography",
    "Applied Linear Algebra",
    "Applied Machine Learning",
    "Applied Machine Learning in Python",
    "Applied Mathematics and Statistical Methods",
    "Applied Numerical methods",
    "Applied Statistics for Health Data Science",
    "Artificial Intelligence",
    "Artificial Neural Networks",
    "Augmented Reality and Virtual Reality",
    "Basic workshop",
    "Behavioural Science",
    "Bigdata Analytics",
    "Bio Inspired Design",
    "Blockchain Technology",
    "Block Chains And Crypto Currencies",
    "Body Area Networks",
    "Biophysics",
    "Calculus and Laplace Transforms",
    "Cloud Application Development",
    "Cloud Computing",
    "Cognitive Analytics",
    "Competitive Coding Practices",
    "Computational Biology and Analytics",
    "Computational Game Theory",
    "Computational Intelligence",
    "Computer Architecture and Organization",
    "Computer Networks",
    "Computer Vision",
    "Cyber Physical Systems",
    "Cyber Security Framework",
    "Data Analytics Using Scala Programming",
    "Data Clinic",
    "Data Mining And Data Warehousing",
    "Data Privacy",
    "Data Structures and Algorithms",
    "Data analysis and visualization",
    "Data engineering",
    "Database Management Systems",
    "Deep Learning",
    "Design Analysis Of Algorithm",
    "Differential And Difference Equations",
    "Digital Logic Design",
    "Discrete Mathematics And Graph Theory",
    "Distributed Systems",
    "Dynamics of workplace communication Skills",
    "Effective Technical Communication",
    "Electric Circuits and Systems",
    "Embedded Computing for IoT",
    "Embedded Systems",
    "Emotional Intelligence",
    "Engineering Chemistry",
    "Engineering Design",
    "Engineering Design and Modelling",
    "Engineering Economics",
    "Engineering Mechanics",
    "Engineering Physics",
    "Environmental Sustainability",
    "Ethical Hacking",
    "Expert Systems and Fuzzy Logic",
    "Forensic Chemistry and Applications",
    "Forensic Science",
    "Foundations of Data Science",
    "Fundamentals in AI & ML",
    "Generative AI",
    "Healthcare Data Analytics",
    "Healthcare Information Systems",
    "High performance Computing",
    "Human Computer Interaction",
    "Human Resource Management",
    "Image Processing and Analysis",
    "Information Retrieval and Web Search",
    "Information Technology & Society",
    "International Business",
    "Internet and Web Programming",
    "Internet of Things",
    "Introduction To E-Commerce",
    "Introduction to Computational Linguistics",
    "Introduction to Computational Physics",
    "Introduction to Computational chemistry",
    "Introduction to Drones",
    "Introduction to Problem Solving and Programming",
    "Introduction to Self-Driving Cars",
    "Introduction to calculus",
    "Introduction to scalable systems",
    "Knowledge Engineering",
    "Lateral Thinking",
    "Machine Learning",
    "Machine learning for large datasets",
    "Mathematical Foundations for Cybersecurity",
    "Medical Imaging",
    "Microprocessors And Microcontrollers",
    "Mobile Application Development",
    "Modeling And Simulation Of Biological Systems",
    "Modeling and Simulation",
    "Object Oriented Programming With C++",
    "Operating System",
    "Operations Research",
    "Optimization Methods in Machine Learning",
    "Parallel and Distributed Computing",
    "Pattern Recognition and Image Analysis",
    "Principles Of Digital Forensics",
    "Principles Of Management And Organizational Behaviour",
    "Probability, Statistics And Reliability",
    "Professional Communication Skills for Engineers",
    "Programming in Java",
    "Python Programming",
    "R Programming",
    "Random Process",
    "Reinforcement Learning",
    "Salesforce",
    "Scalable systems for Data science",
    "Sensors And IoT",
    "Soft Computing",
    "Software Defined Network",
    "Software Engineering",
    "Software Project Management",
    "Software Testing",
    "Statistical Inferences and Series of Function",
    "Stochastic Process",
    "Supply Chain Management",
    "Technology Entrepreneurship",
    "Theory Of Computation And Compiler Design",
    "Time Series Analysis and Its Applications",
    "Unmanned Aerial Vehicles",
    "Virtualization Essentials",
    "Wireless Sensor Networks",
    "Other"
]

// VIT-only colleges for question papers restriction (frontend-only for now)
export const VIT_COLLEGES = [
    "VIT Vellore",
    "VIT Chennai",
    "VIT Bhopal",
    "VIT AP"
]

export const EXAM_TYPES = [
    "Mid-Term",
    "End-Term"
]
